name: rp2350B SparkfunXRP

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: sparkfun_xrp_controller
